context:
  name: aichat
  version: "0.27.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/sigoden/aichat/archive/refs/tags/v${{ version }}.tar.gz
  sha256: eb97284be786b2b625992ab875bb95da2aa3707c063cb0c34521cb01024b38cd

build:
  number: 1

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - aichat --help

about:
  homepage: https://github.com/sigoden/aichat
  summary: All-in-one LLM CLI tool featuring Shell Assistant, Chat-REPL, RAG, AI Tools & Agents, with access to OpenAI, Claude, Gemini, Ollama, Groq, and more.
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - moritzwilksch
