context:
  name: aichat
  version: "0.26.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/sigoden/aichat/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 1743534a68acb9fdf4fee11cd2b38cc5282c85debf89a4052b61a09dcaf51185

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - aichat --help

about:
  homepage: https://github.com/sigoden/aichat
  summary: All-in-one LLM CLI tool featuring Shell Assistant, Chat-REPL, RAG, AI Tools & Agents, with access to OpenAI, Claude, Gemini, Ollama, Groq, and more.
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - moritzwilksch
